import turtle
t=turtle.Screen()
t.screensize(500,800)
t.bgcolor("grey")
cur=turtle.Turtle()
cur.speed(800)
x=cur.xcor()
y=cur.ycor()

cur.penup()
cur.goto(x-250,y-100)
cur.pendown()

cur.fillcolor("Green")
cur.begin_fill()
cur.forward(500)
cur.left(90)
cur.forward(100)
cur.left(90)
cur.forward(500)
cur.left(90)
cur.forward(100)
cur.end_fill()

cur.fillcolor("white")
cur.begin_fill()
cur.backward(100)
cur.left(90)
cur.forward(500)
cur.left(90)
cur.forward(100)
cur.left(90)
cur.forward(500)
cur.left(90)
cur.forward(100)
cur.end_fill()

cur.fillcolor("ORANGE")
cur.begin_fill()
cur.backward(100)
cur.left(90)
cur.forward(500)
cur.left(90)
cur.forward(100)
cur.left(90)
cur.forward(500)
cur.left(90)
cur.forward(100)
cur.end_fill()

cur.color("Blue")
cur.pensize(2)
cur.penup()
cur.goto(x-50,y+50)
cur.pendown()
cur.circle(50)

cur.penup()
cur.goto(x,y+50)
cur.pendown()
for i in range(24):
    cur.forward(50)
    cur.backward(50)
    cur.right(15)


cur.hideturtle()
cur.penup()
cur.goto(x-50,y-200)
cur.write("Jai Hind...",move=False,font=("Arial",30,"italic","underline"))
t.mainloop()